### ISSUE TITLE
add-meta: Get "http://localhost:8091/meta-servers": dial tcp 127.0.0.1:8091: connect: connection refused

### ISSUE THREAD

**Issue by cjt0226** [freetsdb/freetsdb#6]
add meta servers fail. Please check the screenshot
![WX20210716-091609](https://user-images.githubusercontent.com/24307110/125877291-23038758-4c17-4327-b80c-a47cca90cdcf.png)

**Comment by cjt0226** [comment]
![image](https://user-images.githubusercontent.com/24307110/127843409-1b816b83-1ac0-4642-8d4a-365c4b9461d8.png)

**Comment by JZkongfu** [comment]
“no bootstrap needed”说明节点已经在集群中了，下一条log直接说明该节点现在是follower。
是不是配置新集群，但旧数据（/var/lib/freetsdb/meta）没有清除？
可以将旧数据清除下，再试试。

**Comment by cjt0226** [comment]
Resolved by remove /var/lib/freetsdb and reinstall. Thanks
