### ISSUE TITLE
v0.1.2集群单副本RP插入相同数据会重复

### ISSUE THREAD

**Issue by zzm219** [freetsdb/freetsdb#9]
![image](https://user-images.githubusercontent.com/54577069/155993916-1e191193-c403-4315-9d3c-ec06d0c561b5.png)

**Comment by JZkongfu** [comment]
是不是显示查询数据时，时间戳精度被截断了？
先执行下precision ns
再执行下select
试试

**Comment by zzm219** [comment]
插入语句都是一样的，精度也没问题
insert disk_free,hostname=server01 value=442221834240i 1646054117110000000

![image](https://user-images.githubusercontent.com/54577069/156280966-a7e129c8-5622-468b-a73f-ae2de219b190.png)

**Comment by JZkongfu** [comment]
分片机制和分布式迭代器协同上有点问题，这两天会修复下并发布。

**Comment by zzm219** [comment]
具体什么时候会发布啊？

**Comment by JZkongfu** [comment]
月底做个发布

**Comment by zzm219** [comment]
3月底没等到发布，4月份什么时候会发布呢？

**Comment by JZkongfu** [comment]
前段时间有点事情耽搁了下，现在已在调试，预计本周末发布。

**Comment by JZkongfu** [comment]
fixed

**Comment by zzm219** [comment]
副本为1的情况下，该修复会导致SUM方法可能获取不到数据

**Comment by zzm219** [comment]
> fixed



> 固定的



> fixed

副本为1的情况下，该修复会导致SUM方法概率性获取不到数据

**Comment by zzm219** [comment]
> fixed

副本为1的情况下，该修复会导致SUM方法概率性获取不到数据

**Comment by zzm219** [comment]
@JZkongfu 副本为1的情况下，该修复会导致SUM方法概率性获取不到数据
